steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--file=docker/Dockerfile',
      '--tag=eu.gcr.io/$PROJECT_ID/imgproxy:$BRANCH_NAME',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/imgproxy:$BRANCH_NAME']
